blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/sssolutiontec/open-source-catalog/discussions
    about: Ask questions and discuss with other community members
